export const PatientsBusinessConfiguration = {
  ID_MIN_LENGTH: 7,
  ID_MAX_LENGTH: 100,

  FIRSTNAME_MIN_LENGTH: 3,
  FIRSTNAME_MAX_LENGTH: 30,

  LASTNAME_MIN_LENGTH: 3,
  LASTNAME_MAX_LENGTH: 30,

  SUBSTANCE_MIN_LENGTH: 5,
  SUBSTANCE_MAX_LENGTH: 200,

  REACTION_MIN_LENGTH: 5,
  REACTION_MAX_LENGTH: 500,

  CHRONIC_CONDITION_NAME_MIN_LENGTH: 5,
  CHRONIC_CONDITION_NAME_MAX_LENGTH: 100,

  CLINICAL_NOTE_TEXT_MIN_LENGTH: 5,
  CLINICAL_NOTE_TEXT_MAX_LENGTH: 400,

  ICD_MIN_LENGTH: 1,
  ICD_MAX_LENGTH: 16,

  DIAGNOSIS_DESCRIPTION_MIN_LENGTH: 5,
  DIAGNOSIS_DESCRIPTION_MAX_LENGTH: 500,

  PRESCRIPTION_NAME_MIN_LENGTH: 5,
  PRESCRIPTION_NAME_MAX_LENGTH: 200,

  PRESCRIPTION_DOSAGE_MIN_LENGTH: 1,
  PRESCRIPTION_DOSAGE_MAX_LENGTH: 100,

  PRESCRIPTION_INSTRUCTIONS_MIN_LENGTH: 5,
  PRESCRIPTION_INSTRUCTIONS_MAX_LENGTH: 1000,

  ADDENDUM_NOTE_TEXT_MIN_LENGTH: 5,
  ADDENDUM_NOTE_TEXT_MAX_LENGTH: 400,
} as const