version: '3.4'

services:
  appointments.api:
    image: ${DOCKER_REGISTRY-}appointmentsapi
    build:
      context: .
      dockerfile: src/Appointments/Appointments.API/Dockerfile
    depends_on:
      appointments.database:
        condition: service_started
      rabbit.mq:
        condition: service_healthy
    ports:
      - "5200:5200"
    networks:
      - my_network

  gateway.api:
    image: ${DOCKER_REGISTRY-}gatewayapi
    build:
      context: .
      dockerfile: src/Gateway/Gateway.API/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - my_network

  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
      context: .
      dockerfile: src/Users/Users.API/Dockerfile
    ports:
      - "5100:5100"
    depends_on:
        - "users.database"
    networks:
      - my_network
        
  doctors.api:
    image: ${DOCKER_REGISTRY-}doctorsapi
    build:
      context: .
      dockerfile: src/Doctors/Doctors.API/Dockerfile
    ports:
      - "5400:5400"
    depends_on:
      - "doctors.database"
    networks:
      - my_network

  emails.api:
    image: ${DOCKER_REGISTRY-}emailsapi
    build:
      context: .
      dockerfile: src/Emails/Emails.API/Dockerfile
    ports:
      - "5300:5300"
    networks:
      - my_network

  appointments.database:
    image: postgres:latest
    container_name: appointments.database
    environment:
      - POSTGRES_DB=appointments
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - appointments-db:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    restart: always
    networks:
      - my_network

  users.database:
    image: postgres:latest
    container_name: users.database
    environment:
      - POSTGRES_DB=usersdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - users-db:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: always
    networks:
      - my_network
  
  doctors.database:
    image: pgvector/pgvector:pg18-trixie
    container_name: doctors.database
    environment:
      - POSTGRES_DB=doctorsdb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - doctors-db:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    restart: always
    networks:
      - my_network

  rabbit.mq:
    image: rabbitmq:3.11.7-management
    container_name: Queue
    hostname: rabbit-queue
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_logs:/var/log/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: GUEST
      RABBITMQ_DEFAULT_PASS: GUEST
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - my_network

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: Identity
    command: start-dev --import-realm
    environment:
      - KC_HEALTH_ENABLED=true
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
    volumes:
      - ./.containers/identity:/opt/keycloak/data
      - ./.files:/opt/keycloak/data/import
    ports:
      - "18080:8080"
    networks:
      - my_network
  
  ollama:
    container_name: ollama
    image: docker.io/ollama/ollama:latest
    volumes:
      - ./ollama/ollama:/root/.ollama
    ports:
      - "7869:11434"
    environment:
      - OLLAMA_KEEP_ALIVE=24h
    networks:
      - ollama-docker
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [ gpu ]
    restart: unless-stopped
    
volumes:
  rabbitmq_data:
  rabbitmq_logs:
  ollama-data:
  doctors-db:
  appointments-db:
  users-db:

networks:
  ollama-docker:
    external: false
  my_network:
    driver: bridge