export const UsersBusinessConfiguration = {
  ID_MIN_LENGTH: 7,
  ID_MAX_LENGTH: 100,

  FIRSTNAME_MIN_LENGTH: 3,
  FIRSTNAME_MAX_LENGTH: 30,

  LASTNAME_MIN_LENGTH: 3,
  LASTNAME_MAX_LENGTH: 30,

  PASSWORD_MIN_LENGTH: 6,
  PASSWORD_MAX_LENGTH: 30,

  EMAIL_MIN_LENGTH: 9,
  EMAIL_MAX_LENGTH: 40,

  PHONENUMBER_MIN_LENGTH: 8,
  PHONENUMBER_MAX_LENGTH: 16,

  ADDRESS_MIN_LENGTH: 10,
  ADDRESS_MAX_LENGTH: 100,
} as const