export const AppointmentsBusinessConfiguration = {
  ID_MIN_LENGTH: 7,
  ID_MAX_LENGTH: 100,

  PATIENTID_MIN_LENGTH: 7,
  PATIENTID_MAX_LENGTH: 100,

  DOCTORID_MIN_LENGTH: 7,
  DOCTORID_MAX_LENGTH: 100,

  EMAIL_MIN_LENGTH: 9,
  EMAIL_MAX_LENGTH: 40,

  REASON_MAX_LENGTH: 200,
}