// <auto-generated />
using System;
using Doctors.Domain.Entities;
using Doctors.Infrastructure.Features.DBContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Doctors.Infrastructure.Features.Migrations
{
    [DbContext(typeof(DoctorsDbContext))]
    [Migration("20251017081139_Create_Database")]
    partial class Create_Database
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "availabilityexceptiontype", new[] { "extra_availability", "unavailable" });
            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "dayofweek", new[] { "friday", "monday", "saturday", "sunday", "thursday", "tuesday", "wednesday" });
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DoctorSpecialities", b =>
                {
                    b.Property<string>("DoctorId")
                        .HasColumnType("text");

                    b.Property<string>("SpecialityId")
                        .HasColumnType("text");

                    b.HasKey("DoctorId", "SpecialityId");

                    b.HasIndex("SpecialityId");

                    b.ToTable("DoctorSpecialities", (string)null);
                });

            modelBuilder.Entity("Doctors.Domain.Entities.Doctor", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Doctors", (string)null);
                });

            modelBuilder.Entity("Doctors.Domain.Entities.Speciality", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Specialities");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.InboxState", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("Consumed")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConsumerId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<int>("ReceiveCount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Received")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("Delivered");

                    b.ToTable("InboxState");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid?>("ConversationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CorrelationId")
                        .HasColumnType("uuid");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime?>("EnqueueTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ExpirationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FaultAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("text");

                    b.Property<Guid?>("InboxConsumerId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InboxMessageId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("InitiatorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MessageId")
                        .HasColumnType("uuid");

                    b.Property<string>("MessageType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("OutboxId")
                        .HasColumnType("uuid");

                    b.Property<string>("Properties")
                        .HasColumnType("text");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResponseAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("SentTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SourceAddress")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("SequenceNumber");

                    b.HasIndex("EnqueueTime");

                    b.HasIndex("ExpirationTime");

                    b.HasIndex("OutboxId", "SequenceNumber")
                        .IsUnique();

                    b.HasIndex("InboxMessageId", "InboxConsumerId", "SequenceNumber")
                        .IsUnique();

                    b.ToTable("OutboxMessage");
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxState", b =>
                {
                    b.Property<Guid>("OutboxId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Delivered")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long?>("LastSequenceNumber")
                        .HasColumnType("bigint");

                    b.Property<Guid>("LockId")
                        .HasColumnType("uuid");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("OutboxId");

                    b.HasIndex("Created");

                    b.ToTable("OutboxState");
                });

            modelBuilder.Entity("DoctorSpecialities", b =>
                {
                    b.HasOne("Doctors.Domain.Entities.Doctor", null)
                        .WithMany()
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Doctors.Domain.Entities.Speciality", null)
                        .WithMany()
                        .HasForeignKey("SpecialityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Doctors.Domain.Entities.Doctor", b =>
                {
                    b.OwnsMany("Doctors.Domain.Entities.DoctorAvailabilityException", "AvailabilityExceptions", b1 =>
                        {
                            b1.Property<string>("DoctorId")
                                .HasColumnType("text");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("integer");

                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Reason")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("character varying(300)");

                            b1.Property<AvailabilityExceptionType>("Type")
                                .HasColumnType("availabilityexceptiontype");

                            b1.HasKey("DoctorId", "Id");

                            b1.ToTable("DoctorAvailabilityExceptions", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DoctorId");

                            b1.OwnsOne("Shared.Domain.Entities.ValueObjects.DateTimeRange", "Range", b2 =>
                                {
                                    b2.Property<string>("DoctorAvailabilityExceptionDoctorId")
                                        .HasColumnType("text");

                                    b2.Property<int>("DoctorAvailabilityExceptionId")
                                        .HasColumnType("integer");

                                    b2.Property<DateTime>("End")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("End");

                                    b2.Property<DateTime>("Start")
                                        .HasColumnType("timestamp with time zone")
                                        .HasColumnName("Start");

                                    b2.HasKey("DoctorAvailabilityExceptionDoctorId", "DoctorAvailabilityExceptionId");

                                    b2.ToTable("DoctorAvailabilityExceptions");

                                    b2.WithOwner()
                                        .HasForeignKey("DoctorAvailabilityExceptionDoctorId", "DoctorAvailabilityExceptionId");
                                });

                            b1.Navigation("Range")
                                .IsRequired();
                        });

                    b.OwnsOne("Doctors.Domain.Entities.WeeklySchedule", "WeeklySchedule", b1 =>
                        {
                            b1.Property<string>("DoctorId")
                                .HasColumnType("text");

                            b1.HasKey("DoctorId");

                            b1.ToTable("WeeklySchedules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DoctorId");

                            b1.OwnsMany("Doctors.Domain.Entities.WorkDay", "WorkDays", b2 =>
                                {
                                    b2.Property<string>("WeeklyScheduleId")
                                        .HasColumnType("text");

                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("integer");

                                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b2.Property<int>("Id"));

                                    b2.Property<DayOfWeek>("DayOfWeek")
                                        .HasColumnType("dayofweek");

                                    b2.HasKey("WeeklyScheduleId", "Id");

                                    b2.ToTable("WorkDays", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("WeeklyScheduleId");

                                    b2.OwnsMany("Doctors.Domain.Entities.WorkTimeRange", "WorkTimes", b3 =>
                                        {
                                            b3.Property<string>("WorkDayWeeklyScheduleId")
                                                .HasColumnType("text");

                                            b3.Property<int>("WorkDayId")
                                                .HasColumnType("integer");

                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("integer");

                                            NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b3.Property<int>("Id"));

                                            b3.Property<TimeSpan>("End")
                                                .HasColumnType("interval");

                                            b3.Property<TimeSpan>("Start")
                                                .HasColumnType("interval");

                                            b3.HasKey("WorkDayWeeklyScheduleId", "WorkDayId", "Id");

                                            b3.ToTable("WorkTimeRanges", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("WorkDayWeeklyScheduleId", "WorkDayId");
                                        });

                                    b2.Navigation("WorkTimes");
                                });

                            b1.Navigation("WorkDays");
                        });

                    b.Navigation("AvailabilityExceptions");

                    b.Navigation("WeeklySchedule")
                        .IsRequired();
                });

            modelBuilder.Entity("MassTransit.EntityFrameworkCoreIntegration.OutboxMessage", b =>
                {
                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.OutboxState", null)
                        .WithMany()
                        .HasForeignKey("OutboxId");

                    b.HasOne("MassTransit.EntityFrameworkCoreIntegration.InboxState", null)
                        .WithMany()
                        .HasForeignKey("InboxMessageId", "InboxConsumerId")
                        .HasPrincipalKey("MessageId", "ConsumerId");
                });
#pragma warning restore 612, 618
        }
    }
}
