export const DoctorsBusinessConfiguration = {
  ID_MIN_LENGTH: 7,
  ID_MAX_LENGTH: 100,

  SPECIALITY_MIN_LENGTH: 2,
  SPECIALITY_MAX_LENGTH: 30,

  SYMPTOMS_MIN_LENGTH: 2,
  SYMPTOMS_MAX_LENGTH: 300,

  BIO_MIN_LENGTH: 10,
  BIO_MAX_LENGTH: 500,

  REASON_MAX_LENGTH: 200,

  FIRSTNAME_MIN_LENGTH: 3,
  FIRSTNAME_MAX_LENGTH: 30,

  LASTNAME_MIN_LENGTH: 3,
  LASTNAME_MAX_LENGTH: 30,
} as const