namespace Doctors.Domain.Utilities.Strings;

public static class Specialities
{
    public static readonly Dictionary<string, string> MedicalSpecialties =
        new(StringComparer.OrdinalIgnoreCase)
        {
            ["Adolescent medicine"] = "Adolescent medicine focuses on health problems in teenagers including hormones, growth, mood changes, injuries, and chronic illness.",
            ["Aerospace medicine"] = "Aerospace medicine deals with health issues related to flying and air pressure such as motion sickness, oxygen problems, and fatigue.",
            ["Allergy and immunology"] = "This field treats allergies, asthma, immune system disorders, chronic cough, rashes, and sinus problems.",
            ["Anesthesiology"] = "Anesthesiology involves anesthesia, pain control, and monitoring patients during surgery.",
            ["Bariatrics"] = "Bariatrics focuses on weight loss, obesity, metabolic problems, and nutrition guidance.",
            ["Cardiology"] = "Cardiology treats heart and blood vessel issues such as chest pain, palpitations, high blood pressure, and heart disease.",
            ["Cardiothoracic surgery"] = "Cardiothoracic surgery performs surgical treatment on the heart, lungs, and chest organs.",
            ["Child and adolescent psychiatry"] = "This treats emotional, behavioral, and mental health problems in children and teenagers.",
            ["Clinical neurophysiology"] = "Clinical neurophysiology studies nerve and brain activity, diagnosing seizures, neuropathy, and nerve pain.",
            ["Colorectal surgery"] = "Colorectal surgery treats diseases of the colon, rectum, hemorrhoids, bowel problems, and cancers.",
            ["Dermatology"] = "Dermatology treats skin, hair, and nail problems such as rashes, acne, itching, infections, and growths.",
            ["Developmental pediatrics"] = "This focuses on childhood development issues such as ADHD, autism, and learning delays.",
            ["Emergency medicine"] = "Emergency medicine handles urgent injuries, trauma, sudden illness, chest pain, fractures, and severe infections.",
            ["Endocrinology"] = "Endocrinology treats hormone disorders like diabetes, thyroid problems, weight changes, and fatigue.",
            ["Family medicine"] = "Family medicine provides general care for all ages including infections, fevers, chronic disease, and preventive health.",
            ["Forensic pathology"] = "Forensic pathology determines causes of death through medical examination.",
            ["Forensic psychiatry"] = "Forensic psychiatry evaluates mental health in legal and criminal situations.",
            ["Gastroenterology"] = "Gastroenterology treats digestive issues like stomach pain, nausea, diarrhea, constipation, and liver disease.",
            ["General surgery"] = "General surgery performs operations for abdominal, soft tissue, and emergency surgical conditions.",
            ["Geriatric psychiatry"] = "Geriatric psychiatry focuses on mental health in older adults, including memory problems and mood disorders.",
            ["Geriatrics"] = "Geriatrics cares for older adults with chronic illness, frailty, memory problems, and mobility issues.",
            ["Gynecologic oncology"] = "Gynecologic oncology treats cancers of the female reproductive system.",
            ["Hematologic pathology"] = "Hematologic pathology diagnoses blood disorders using laboratory analysis.",
            ["Hematology"] = "Hematology treats blood diseases including anemia, clotting issues, leukemia, and bleeding disorders.",
            ["Infectious disease"] = "Infectious disease treats bacterial, viral, and unusual infections, fevers, and long-lasting illness.",
            ["Intensive care medicine"] = "ICU medicine treats critically ill patients who need life support and close monitoring.",
            ["Internal medicine"] = "Internal medicine treats complex adult illnesses such as infections, lung issues, heart problems, and chronic disease.",
            ["Interventional radiology"] = "This specialty performs minimally invasive procedures using imaging guidance.",
            ["Maternal-fetal medicine"] = "Maternal-fetal medicine handles high-risk pregnancies and fetal complications.",
            ["Medical biochemistry"] = "Medical biochemistry studies chemical processes in the body related to disease diagnosis.",
            ["Medical genetics"] = "Medical genetics diagnoses inherited disorders and genetic conditions.",
            ["Medical oncology"] = "Medical oncology treats cancer with medications such as chemotherapy and immunotherapy.",
            ["Neonatology"] = "Neonatology treats newborn infants, especially premature or medically fragile babies.",
            ["Nephrology"] = "Nephrology treats kidney disease, electrolyte problems, swelling, and kidney failure.",
            ["Neurology"] = "Neurology treats brain and nerve problems such as headaches, seizures, numbness, weakness, and nerve pain.",
            ["Neuropathology"] = "Neuropathology studies diseases of the brain and nerves using tissue analysis.",
            ["Neuropsychiatry"] = "Neuropsychiatry treats mental and neurological disorders involving both brain function and behavior.",
            ["Neuroradiology"] = "Neuroradiology uses imaging to diagnose brain, spinal cord, and nerve problems.",
            ["Neurosurgery"] = "Neurosurgery performs surgery on the brain, spine, and nerves.",
            ["Nuclear medicine"] = "Nuclear medicine uses radioactive substances for imaging and targeted treatment.",
            ["Obstetrics and gynecology"] = "OB/GYN treats pregnancy, childbirth, menstrual issues, infertility, and female reproductive health.",
            ["Occupational medicine"] = "Occupational medicine treats work-related injuries, strain, chemical exposure, and ergonomic issues.",
            ["Ophthalmology"] = "Ophthalmology treats eye problems including vision loss, infections, cataracts, and injuries.",
            ["Oral and maxillofacial surgery"] = "This performs surgery on the mouth, jaw, face, and teeth.",
            ["Orthopedic surgery"] = "Orthopedics treats bones, joints, muscles, the spine, sports injuries, back pain, fractures, and arthritis.",
            ["Otorhinolaryngology"] = "ENT treats ear, nose, throat, sinus, voice, and hearing problems.",
            ["Palliative care"] = "Palliative care relieves symptoms and pain for patients with serious illness.",
            ["Pathology"] = "Pathology studies tissues and fluids to diagnose diseases.",
            ["Pediatric allergy and immunology"] = "This treats allergies, asthma, and immune problems in children.",
            ["Pediatric cardiology"] = "Pediatric cardiology treats heart problems in children.",
            ["Pediatric emergency medicine"] = "This focuses on emergency care for children.",
            ["Pediatric endocrinology"] = "This treats hormone disorders in children such as diabetes and growth issues.",
            ["Pediatric gastroenterology"] = "This treats digestive problems in children.",
            ["Pediatric hematology and oncology"] = "This treats blood disorders and cancer in children.",
            ["Pediatric infectious disease"] = "This treats complex infections in children.",
            ["Pediatric nephrology"] = "This treats kidney problems in children.",
            ["Pediatric respiratory medicine"] = "This treats lung and breathing problems in children including asthma and chronic cough.",
            ["Pediatric rheumatology"] = "This treats autoimmune and joint issues in children.",
            ["Pediatric surgery"] = "Pediatric surgery performs operations on infants and children.",
            ["Pediatrics"] = "General pediatrics treats common childhood illnesses like fever, cough, infections, and stomach issues.",
            ["Physical medicine and rehabilitation"] = "PM&R treats back pain, mobility issues, injuries, nerve pain, and restores physical function.",
            ["Plastic, reconstructive and aesthetic surgery"] = "Plastic surgery repairs injuries and improves appearance after trauma or disease.",
            ["Psychiatry"] = "Psychiatry treats mental health problems like anxiety, depression, mood changes, and sleep issues.",
            ["Public health"] = "Public health deals with disease prevention, epidemics, and population health.",
            ["Pulmonology"] = "Pulmonology treats lung and breathing problems such as asthma, chronic cough, pneumonia, and chest tightness.",
            ["Radiation oncology"] = "Radiation oncology treats cancer using radiation therapy.",
            ["Radiology"] = "Radiology uses imaging such as X-ray, CT, and MRI to diagnose disease.",
            ["Reproductive endocrinology and infertility"] = "This treats infertility, hormone imbalance, and reproductive issues.",
            ["Rheumatology"] = "Rheumatology treats joint pain, autoimmune disease, inflammation, and arthritis.",
            ["Sports medicine"] = "Sports medicine treats injuries from exercise including sprains, strains, knee pain, and shoulder injuries.",
            ["Surgical oncology"] = "Surgical oncology performs operations to remove cancer.",
            ["Thoracic surgery"] = "Thoracic surgery treats lung, chest, and esophagus conditions.",
            ["Toxicology"] = "Toxicology manages poisoning, overdoses, and exposure to toxic substances.",
            ["Transfusion medicine"] = "Transfusion medicine manages blood transfusions and immune reactions.",
            ["Urology"] = "Urology treats urinary problems, kidney stones, male reproductive issues, and bladder problems.",
            ["Vascular surgery"] = "Vascular surgery treats blood vessel disease, poor circulation, and aneurysms."
        };
}