namespace Doctors.Domain.Utilities.Strings;

public static class Specialities
{
    public static readonly string[] MedicalSpecialties =
    {
        "Adolescent medicine",
        "Aerospace medicine",
        "Allergy and immunology",
        "Anesthesiology",
        "Bariatrics",
        "Cardiology",
        "Cardiothoracic surgery",
        "Child and adolescent psychiatry",
        "Clinical neurophysiology",
        "Colorectal surgery",
        "Dermatology",
        "Developmental pediatrics",
        "Emergency medicine",
        "Endocrinology",
        "Family medicine",
        "Forensic pathology",
        "Forensic psychiatry",
        "Gastroenterology",
        "General surgery",
        "Geriatric psychiatry",
        "Geriatrics",
        "Gynecologic oncology",
        "Hematologic pathology",
        "Hematology",
        "Infectious disease",
        "Intensive care medicine",
        "Internal medicine",
        "Interventional radiology",
        "Maternal-fetal medicine",
        "Medical biochemistry",
        "Medical genetics",
        "Medical oncology",
        "Neonatology",
        "Nephrology",
        "Neurology",
        "Neuropathology",
        "Neuropsychiatry",
        "Neuroradiology",
        "Neurosurgery",
        "Nuclear medicine",
        "Obstetrics and gynecology",
        "Occupational medicine",
        "Ophthalmology",
        "Oral and maxillofacial surgery",
        "Orthopedic surgery",
        "Otorhinolaryngology",
        "Palliative care",
        "Pathology",
        "Pediatric allergy and immunology",
        "Pediatric cardiology",
        "Pediatric emergency medicine",
        "Pediatric endocrinology",
        "Pediatric gastroenterology",
        "Pediatric hematology and oncology",
        "Pediatric infectious disease",
        "Pediatric nephrology",
        "Pediatric respiratory medicine",
        "Pediatric rheumatology",
        "Pediatric surgery",
        "Pediatrics",
        "Physical medicine and rehabilitation",
        "Plastic, reconstructive and aesthetic surgery",
        "Psychiatry",
        "Public health",
        "Pulmonology",
        "Radiation oncology",
        "Radiology",
        "Reproductive endocrinology and infertility",
        "Rheumatology",
        "Sports medicine",
        "Surgical oncology",
        "Thoracic surgery",
        "Toxicology",
        "Transfusion medicine",
        "Urology",
        "Vascular surgery"
    };
}