name: CD

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

jobs:
  docker-build-push:
    if: ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'master' }}
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGE_NAMESPACE: inad12

    strategy:
      matrix:
        include:
          - name: Appointments
            image: appointments
          - name: Emails
            image: emails
          - name: Gateway
            image: gateway
          - name: Users
            image: users

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ matrix.image }}
          DOCKERFILE_PATH=src/${{ matrix.name }}/${{ matrix.name }}.API/Dockerfile
      
          echo "Building image: $IMAGE_NAME"
          docker build --progress=plain -f $DOCKERFILE_PATH -t $IMAGE_NAME:latest -t $IMAGE_NAME:${{ github.sha }} .
      
          echo "Pushing image: $IMAGE_NAME"
          docker push $IMAGE_NAME:latest
          docker push $IMAGE_NAME:${{ github.sha }}


