name: CI/CD Pipeline

on:
  push:
    branches: [master]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAMESPACE: inad12

jobs:
  build-test-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [Appointments, Emails, Gateway, Users]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.IMAGE_NAMESPACE }}
          password: ${{ secrets.CR_PAT }}

      - name: Restore and build
        run: |
          dotnet restore src/${{ matrix.service }}/${{ matrix.service }}.API/${{ matrix.service }}.API.csproj
          dotnet build src/${{ matrix.service }}/${{ matrix.service }}.API/${{ matrix.service }}.API.csproj --no-restore --configuration Release

      - name: Run Unit Tests
        run: |
          dotnet test tests/${{ matrix.service }}/${{ matrix.service }}.Application.UnitTests/${{ matrix.service }}.Application.UnitTests.csproj --no-build --logger trx

      - name: Run Integration Tests
        run: |
          dotnet test tests/${{ matrix.service }}/${{ matrix.service }}.Application.IntegrationTests/${{ matrix.service }}.Application.IntegrationTests.csproj --no-build --logger trx

      - name: Build Docker image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ matrix.service | toLower }}
          docker build -f src/${{ matrix.service }}/${{ matrix.service }}.API/Dockerfile -t $IMAGE_NAME:latest src/${{ matrix.service }}/${{ matrix.service }}.API

      - name: Push Docker image
        run: |
          IMAGE_NAME=${{ env.REGISTRY }}/${{ env.IMAGE_NAMESPACE }}/${{ matrix.service | toLower }}
          docker push $IMAGE_NAME:latest
