name: CI

on:
  push:
    branches:
      - master
      - development
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Cache NuGet packages
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: nuget-${{ runner.os }}-${{ hashFiles('**/packages.lock.json') }}
          restore-keys: |
            nuget-${{ runner.os }}-

      - name: Restore
        run: dotnet restore "./Healthcare Appointment and Management System.sln"

      - name: Build
        run: dotnet build "./Healthcare Appointment and Management System.sln" --configuration Release --no-restore 

      - name: Run tests
        run: dotnet test "./Healthcare Appointment and Management System.sln" --configuration Release  --no-restore --no-build
